on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CRED }}

      # Deploy ARM template
    - name: Run ARM deploy with ARM template
      id: deployarm
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: 25d4753f-341d-4ce7-8641-646cf928294c
        resourceGroupName: hqtestrg
        template: ./Storage.template.json
        parameters: storageAccountType=Standard_LRS storageAccountName=hqtestadls2arm
      # Deploy ARM template
    - name: Run ARM deploy with Biecp
      id: deploybicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: 25d4753f-341d-4ce7-8641-646cf928294c
        resourceGroupName: hqtestrg
        template: ./Storage.bicep
        parameters: storageAccountType=Standard_LRS storageAccountName=hqtestadls2bicep

      # output containerName variable from template
    - run: echo ${{ steps.deploybicep.outputs.resourceIds }}
    - run: echo ${{ steps.deployarm.outputs.resourceIds }}
